# User Settings | Edit there as per required

title: accent
url: "https://hyowonee.github.io"
baseurl: "/"

# This will show up at the top of index page
site_heading: >
    효원이<span class="faded">의 블로그</span>

email: popopowon@gmail.com
author: Choi Hyowon
# This description will show up in google search results
# (for index page) etc.
description: >
    효원이의 블로그

# This will what will show against &copy; in the footer
copyright: Choi Hyowon
# Toggle your short bio, which will displayed on your index page
# Just toggle it and run jekyll again to see
intro: false         # Tip: Remove the span from site_heading if intro is set to true
# This will be displayed in your intro
short_bio: >
    효원이의 블로그입니다.

permalink: /:title.html

# Comments are powered by disqus
comments: true

# keep about_stub roughly 12 words long for best results
# This will show up at the bottom of each post
# Note that about_footer should be true if you want
# to see author information at the bottom of each post
about_stub: >
    열심히 공부 중 입니다.

about_footer: true

#twitter_username: AnkitSultana
github_username: hyowonee
facebook_id: popopowon

favicon: true
favicon_location: "images/favicon.ico"

profile_picture: images/profile.png
paginate: 5
paginate_path: "/page/:num"
#tracking_id: UA-69243698-7 # GA Tracking ID

# Social Stuff | open graph and twitter cards
#og_image: "images/accent.png" # This will show in facebook thumbnails
#twitter_image: "http://ankitsultana.com/images/accent.png?1234" # This will show in twitter cards

####################################
####################################
####################################
### Build Settings | Don't Touch ###
####################################
####################################
####################################

markdown: kramdown

plugins:
    - jekyll-paginate

sass:
    style: compressed
    sass_dir: _sass

# Scopes
defaults:
    -
        scope:
            path:   ""
            type:   "pages"
        values:
            layout: "page"
    -
        scope:
            path:   ""
            type:   "posts"
        values:
            layout: "post"

exclude: [vendor] # For travis ci
